sudo: required

addons:
  # service for code quality analysis
  sonarqube:
    organization: "kitteh6660-github"

# travis-ci does not support actionscript.
# However the build uses ant, which is usually used to build java projects.
# The ant task (mxmlc) provided by the flex SDK (ant/lib/flexTasks.jar) is used to build the project.
language: java

before_install:
  - sudo apt-get update
  # install VNC and xfce4 so we have a desktop, as the flash player requires one
  - sudo apt-get install vnc4server xfce4 ant ant-optional -y

install:
  # Java 7 is used by default, but sonar requires java 8
  - jdk_switcher  use oraclejdk8
  # download and install the flex SDK and the flash player
  - devTools/ci/setup-flex.sh
  # start a VNC session, this will be the desktop for tests
  - Xvnc :1 &
 
script:
    # this is where the build happens. A separate build is started for every entry in the matrix element
  - ant test-$BUILD
  - devTools/ci/update-sonar-version.sh

after_success:
  - sonar-scanner

env:
  global:
    # tell the build file where to find the flex SDK
    - FLEX_HOME=flex/"
    # this is to trick the flash player into thinking it is running on a desktop
    - DISPLAY=":1"
  matrix:
    # different configurations that should be built
    - BUILD="release"
    - BUILD="debug"

# Just so Travis.CI won't complain about Vanilla+ failing, since V+ wasn't intended to use Travis.
branches:
  except:
    VanillaPlus

